/*
   Add transmogrifier NPC
   ----------------------
   With a gm account goto the location you want (position and orientation) to
   add the npc and use this command:
   .npc add 190010
*/

/* ---------------------------- */
/* *Everywhere* flying mount.  */
/* -------------------------- */
/* .additem 701000           */
DELETE FROM `item_template` WHERE `entry`=701000;
INSERT INTO `item_template` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`, `name`,                `displayid`, `Quality`,   `Flags`, `FlagsExtra`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `RequiredSkill`, `RequiredSkillRank`, `requiredspell`, `requiredhonorrank`, `RequiredCityRank`, `RequiredReputationFaction`, `RequiredReputationRank`, `maxcount`, `stackable`, `ContainerSlots`, `StatsCount`, `stat_type1`, `stat_value1`, `stat_type2`, `stat_value2`, `stat_type3`, `stat_value3`, `stat_type4`, `stat_value4`, `stat_type5`, `stat_value5`, `stat_type6`, `stat_value6`, `stat_type7`, `stat_value7`, `stat_type8`, `stat_value8`, `stat_type9`, `stat_value9`, `stat_type10`, `stat_value10`, `ScalingStatDistribution`, `ScalingStatValue`, `dmg_min1`, `dmg_max1`, `dmg_type1`, `dmg_min2`, `dmg_max2`, `dmg_type2`, `armor`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `delay`, `ammo_type`, `RangedModRange`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `spellppmRate_1`, `spellcooldown_1`, `spellcategory_1`, `spellcategorycooldown_1`, `spellid_2`, `spelltrigger_2`, `spellcharges_2`, `spellppmRate_2`, `spellcooldown_2`, `spellcategory_2`, `spellcategorycooldown_2`, `spellid_3`, `spelltrigger_3`, `spellcharges_3`, `spellppmRate_3`, `spellcooldown_3`, `spellcategory_3`, `spellcategorycooldown_3`, `spellid_4`, `spelltrigger_4`, `spellcharges_4`, `spellppmRate_4`, `spellcooldown_4`, `spellcategory_4`, `spellcategorycooldown_4`, `spellid_5`, `spelltrigger_5`, `spellcharges_5`, `spellppmRate_5`, `spellcooldown_5`, `spellcategory_5`, `spellcategorycooldown_5`, `bonding`, `description`,            `PageText`, `LanguageID`, `PageMaterial`, `startquest`, `lockid`, `Material`, `sheath`, `RandomProperty`, `RandomSuffix`, `block`, `itemset`, `MaxDurability`, `area`, `Map`, `BagFamily`, `TotemCategory`, `socketColor_1`, `socketContent_1`, `socketColor_2`, `socketContent_2`, `socketColor_3`, `socketContent_3`, `socketBonus`, `GemProperties`, `RequiredDisenchantSkill`, `ArmorDamageModifier`, `duration`, `ItemLimitCategory`, `HolidayId`, `ScriptName`, `DisenchantID`, `FoodType`, `minMoneyLoot`, `maxMoneyLoot`, `flagsCustom`, `VerifiedBuild`)
                     VALUES (701000,        9,          0,                      -1, 'Tome of World Flying',      61330,         7, 134217792,            0,           1,   4500000,     4500000,               0,               -1,              -1,          80,              45,               0,                   0,               0,                   0,                  0,                           0,                        0,          0,           1,                0,            0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,             0,              0,                         0,                  0,          0,          0,           0,          0,          0,           0,       0,          0,          0,            0,           0,            0,            0,    1000,           0,                0,         483,                0,               -1,                0,                -1,                 0,                        -1,       31700,                6,                0,                0,                -1,                 0,                        -1,           0,                0,                0,                0,                -1,                 0,                        -1,           0,                0,                0,                0,                -1,                 0,                        -1,           0,                0,                0,                0,                -1,                 0,                        -1,         0, 'Learn to fly everywhere',         0,            0,              0,            0,        0,          8,        0,                0,              0,       0,         0,               0,      0,     0,           0,               0,               0,                 0,               0,                 0,               0,                 0,             0,               0,                        -1,                     0,          0,                   0,           0,           '',              0,          0,              0,              0,             0,               1);

/* --------------------- */
/* Change stack sizes.  */
/* ------------------- */

/* Change stack sizes for misc materials.  */
/* --------------------------------------- */
UPDATE item_template SET stackable=200 WHERE name="Heavy Frostweave Bandage";
UPDATE item_template SET stackable=250 WHERE name="Dark Iron Residue";

/* Change stack sizes for clothes.  */
/* -------------------------------- */
UPDATE item_template SET stackable=200 WHERE name="Linen Cloth";
UPDATE item_template SET stackable=200 WHERE name="Wool Cloth";
UPDATE item_template SET stackable=200 WHERE name="Silk Cloth";
UPDATE item_template SET stackable=200 WHERE name="Mageweave Cloth";
UPDATE item_template SET stackable=200 WHERE name="Runecloth";
UPDATE item_template SET stackable=200 WHERE name="Netherweave Cloth";
UPDATE item_template SET stackable=200 WHERE name="FrostWeave Cloth";
UPDATE item_template SET stackable=200 WHERE name="Soul Essence";

/* Change stack sizes for essence materials.  */
/* ------------------------------------------ */
UPDATE item_template SET stackable=200 WHERE name="Primal Earth";
UPDATE item_template SET stackable=200 WHERE name="Primal Water";
UPDATE item_template SET stackable=200 WHERE name="Primal Air";
UPDATE item_template SET stackable=200 WHERE name="Primal Fire";
UPDATE item_template SET stackable=200 WHERE name="Primal Shadow";
UPDATE item_template SET stackable=200 WHERE name="Primal Life";
UPDATE item_template SET stackable=200 WHERE name="Primal Mana";
UPDATE item_template SET stackable=200 WHERE name="Eternal Earth";
UPDATE item_template SET stackable=200 WHERE name="Eternal Water";
UPDATE item_template SET stackable=200 WHERE name="Eternal Air";
UPDATE item_template SET stackable=200 WHERE name="Eternal Fire";
UPDATE item_template SET stackable=200 WHERE name="Eternal Shadow";
UPDATE item_template SET stackable=200 WHERE name="Eternal Life";

/* Change stack sizes for mining materials.  */
/* ----------------------------------------- */
UPDATE item_template SET stackable=200 WHERE name="Copper Bar";
UPDATE item_template SET stackable=200 WHERE name="Tin Bar";
UPDATE item_template SET stackable=200 WHERE name="Bronze Bar";
UPDATE item_template SET stackable=200 WHERE name="Silver Bar";
UPDATE item_template SET stackable=200 WHERE name="Iron Bar";
UPDATE item_template SET stackable=200 WHERE name="Steel Bar";
UPDATE item_template SET stackable=200 WHERE name="Gold Bar";
UPDATE item_template SET stackable=200 WHERE name="Mithril Bar";
UPDATE item_template SET stackable=200 WHERE name="Truesilver Bar";
UPDATE item_template SET stackable=200 WHERE name="Thorium Bar";
UPDATE item_template SET stackable=200 WHERE name="Enchanted Thorium Bar";
UPDATE item_template SET stackable=200 WHERE name="Fel Iron Bar";
UPDATE item_template SET stackable=200 WHERE name="Adamantite Bar";
UPDATE item_template SET stackable=200 WHERE name="Hardened Adamantite Bar";
UPDATE item_template SET stackable=200 WHERE name="Eternium Bar";
UPDATE item_template SET stackable=200 WHERE name="Felsteel Bar";
UPDATE item_template SET stackable=200 WHERE name="Khorium Bar";
UPDATE item_template SET stackable=200 WHERE name="Cobalt Bar";
UPDATE item_template SET stackable=200 WHERE name="Saronite Bar";
UPDATE item_template SET stackable=200 WHERE name="Titanium Bar";

/* Change stack size for gems. */
/* --------------------------- */
/* White gems */
UPDATE item_template SET stackable=200 WHERE name="Bold Tourmaline";
UPDATE item_template SET stackable=200 WHERE name="Delicate Tourmaline";
UPDATE item_template SET stackable=200 WHERE name="Teardrop Tourmaline";
UPDATE item_template SET stackable=200 WHERE name="Runed Tourmaline";
UPDATE item_template SET stackable=200 WHERE name="Bright Tourmaline";
UPDATE item_template SET stackable=200 WHERE name="Solid Zircon";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Zircon";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Zircon";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Amber";
UPDATE item_template SET stackable=200 WHERE name="Smooth Amber";
UPDATE item_template SET stackable=200 WHERE name="Rigid Amber";
UPDATE item_template SET stackable=200 WHERE name="Gleaming Amber";
UPDATE item_template SET stackable=200 WHERE name="Thick Amber";

/* Green gems */
UPDATE item_template SET stackable=200 WHERE name="Accurate Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Aquamarine";
UPDATE item_template SET stackable=200 WHERE name="Arcane Crystal";
UPDATE item_template SET stackable=200 WHERE name="Azerothian Diamond";
UPDATE item_template SET stackable=200 WHERE name="Azure Moonstone";
UPDATE item_template SET stackable=200 WHERE name="Balanced Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Balanced Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Black Pearl";
UPDATE item_template SET stackable=200 WHERE name="Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Blood of the Mountain";
UPDATE item_template SET stackable=200 WHERE name="Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Blue Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Bold Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Bold Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Bright Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Bright Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Champion's Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Citrine";
UPDATE item_template SET stackable=200 WHERE name="Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Deadly Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Defender's Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Deft Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Delicate Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Delicate Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Durable Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Empowered Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Enchanted Pearl";
UPDATE item_template SET stackable=200 WHERE name="Enduring Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Enduring Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Energized Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Etched Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Fierce Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Flashing Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Forceful Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Fractured Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Gleaming Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Glimmering Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Glinting Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Glinting Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Glowing Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Glowing Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Golden Pearl";
UPDATE item_template SET stackable=200 WHERE name="Great Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Guardian's Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Huge Emerald";
UPDATE item_template SET stackable=200 WHERE name="Infused Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Infused Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Intricate Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Iridescent Pearl";
UPDATE item_template SET stackable=200 WHERE name="Jade";
UPDATE item_template SET stackable=200 WHERE name="Jaggal Pearl";
UPDATE item_template SET stackable=200 WHERE name="Jagged Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Jagged Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Lambent Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Large Opal";
UPDATE item_template SET stackable=200 WHERE name="Lesser Moonstone";
UPDATE item_template SET stackable=200 WHERE name="Lucent Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Luminous Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Luminous Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Azure Moonstone";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Malachite";
UPDATE item_template SET stackable=200 WHERE name="Misty Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Moss Agate";
UPDATE item_template SET stackable=200 WHERE name="Mysterious Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Mystic Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Northsea Pearl";
UPDATE item_template SET stackable=200 WHERE name="Opaque Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Accurate Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Balanced Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Bold Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Bright Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Brilliant Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Champion's Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Dazzling Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Deadly Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Defender's Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Deft Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Delicate Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Durable Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Empowered Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Enduring Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Energized Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Etched Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Fierce Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Flashing Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Forceful Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Fractured Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Glimmering Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Glinting Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Glowing Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Guardian's Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Infused Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Inscribed Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Intricate Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Jagged Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Lambent Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Lucent Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Luminous Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Lustrous Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Perfect Misty Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Mysterious Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Mystic Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Opaque Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Potent Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Precise Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Pristine Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Puissant Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Purified Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Quick Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Radiant Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Reckless Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Regal Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Resolute Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Resplendent Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Rigid Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Royal Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Runed Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Seer's Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Shattered Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Shifting Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Shining Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Smooth Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Solid Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Perfect Sovereign Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Sparkling Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Perfect Stalwart Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Stark Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Steady Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Stormy Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Perfect Subtle Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Perfect Sundered Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Tense Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Tenuous Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Thick Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Perfect Timeless Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Turbid Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Veiled Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Perfect Vivid Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Perfect Wicked Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Potent Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Potent Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Precise Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Prismatic Black Diamond";
UPDATE item_template SET stackable=200 WHERE name="Pristine Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Puissant Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Purified Jaggal Pearl";
UPDATE item_template SET stackable=200 WHERE name="Purified Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Quick Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Radiant Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Radiant Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Reckless Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Regal Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Resolute Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Resplendent Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Rigid Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Rigid Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Royal Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Royal Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Runed Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Runed Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Seer's Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Shadow Pearl";
UPDATE item_template SET stackable=200 WHERE name="Shadowgem";
UPDATE item_template SET stackable=200 WHERE name="Shattered Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Shifting Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Shifting Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Shining Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Small Lustrous Pearl";
UPDATE item_template SET stackable=200 WHERE name="Smooth Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Smooth Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Solid Azure Moonstone";
UPDATE item_template SET stackable=200 WHERE name="Solid Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Souldarite";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Shadow Draenite";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Azure Moonstone";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Stalwart Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Star Ruby";
UPDATE item_template SET stackable=200 WHERE name="Stark Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Steady Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Stormy Azure Moonstone";
UPDATE item_template SET stackable=200 WHERE name="Stormy Chalcedony";
UPDATE item_template SET stackable=200 WHERE name="Subtle Bloodstone";
UPDATE item_template SET stackable=200 WHERE name="Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Sundered Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Teardrop Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Tense Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Tenuous Shadow Crystal";
UPDATE item_template SET stackable=200 WHERE name="Thick Golden Draenite";
UPDATE item_template SET stackable=200 WHERE name="Thick Sun Crystal";
UPDATE item_template SET stackable=200 WHERE name="Tigerseye";
UPDATE item_template SET stackable=200 WHERE name="Timeless Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Turbid Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Veiled Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Veiled Huge Citrine";
UPDATE item_template SET stackable=200 WHERE name="Vivid Dark Jade";
UPDATE item_template SET stackable=200 WHERE name="Wicked Flame Spessarite";
UPDATE item_template SET stackable=200 WHERE name="Wicked Huge Citrine";

/* Blue gems */
UPDATE item_template SET stackable=200 WHERE name="Accurate Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Austere Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Balanced Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Balanced Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Barbed Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Barbed Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Beaming Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Bold Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bold Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bracing Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Bracing Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Bright Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bright Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Brutal Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Champion's Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Chaotic Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Chaotic Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Chromatic Sphere";
UPDATE item_template SET stackable=200 WHERE name="Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Talasite";
UPDATE item_template SET stackable=200 WHERE name="Deadly Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Defender's Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Deft Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Delicate Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Delicate Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Destructive Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Destructive Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Don Amancio's Heart";
UPDATE item_template SET stackable=200 WHERE name="Don Rodrigo's Heart";
UPDATE item_template SET stackable=200 WHERE name="Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Durable Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Effulgent Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Ember Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Ember Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Empowered Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Enchanted Tear";
UPDATE item_template SET stackable=200 WHERE name="Enduring Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Enduring Talasite";
UPDATE item_template SET stackable=200 WHERE name="Energized Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Enigmatic Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Enigmatic Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Enigmatic Starflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Etched Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Eternal Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Eternal Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Eye of the Sea";
UPDATE item_template SET stackable=200 WHERE name="Fierce Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Flashing Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Flashing Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Forceful Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Forceful Talasite";
UPDATE item_template SET stackable=200 WHERE name="Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Forlorn Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Forlorn Starflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Fractured Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Gleaming Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Glimmering Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Glinting Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Glinting Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Glowing Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Glowing Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Great Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Guardian's Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Heavy Tonk Armor";
UPDATE item_template SET stackable=200 WHERE name="Imbued Unstable Diamond";
UPDATE item_template SET stackable=200 WHERE name="Impassive Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Impassive Starflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Infinite Sphere";
UPDATE item_template SET stackable=200 WHERE name="Infused Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Infused Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Insightful Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Insightful Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Intricate Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Invigorating Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Jagged Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Jagged Talasite";
UPDATE item_template SET stackable=200 WHERE name="Juno's Test Gem";
UPDATE item_template SET stackable=200 WHERE name="Lambent Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Lucent Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Luminous Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Luminous Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Sky Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Star of Elune";
UPDATE item_template SET stackable=200 WHERE name="Mighty Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Mighty Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Misty Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Mysterious Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Mystic Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Mystic Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Mystical Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Notched Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Notched Deep Peridot";
UPDATE item_template SET stackable=200 WHERE name="Opaque Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Persistent Earthshatter Diamond";
UPDATE item_template SET stackable=200 WHERE name="Persistent Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Potent Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Potent Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Potent Unstable Diamond";
UPDATE item_template SET stackable=200 WHERE name="Powerful Earthshatter Diamond";
UPDATE item_template SET stackable=200 WHERE name="Powerful Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Powerful Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Precise Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Prismatic Sphere";
UPDATE item_template SET stackable=200 WHERE name="Pristine Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Puissant Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Purified Shadow Pearl";
UPDATE item_template SET stackable=200 WHERE name="Purified Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Quick Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Quick Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Radiant Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Radiant Talasite";
UPDATE item_template SET stackable=200 WHERE name="Reckless Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Reckless Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Regal Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Regal Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Relentless Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Relentless Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Resolute Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Resplendent Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Revitalizing Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Riding Crop";
UPDATE item_template SET stackable=200 WHERE name="Rigid Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Rigid Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Royal Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Royal Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Runed Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Runed Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Seer's Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Shattered Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Shifting Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Shifting Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Shining Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Siren's Tear";
UPDATE item_template SET stackable=200 WHERE name="Sky Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Smooth Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Smooth Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Solid Sky Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Solid Sky Sapphire (Unused)";
UPDATE item_template SET stackable=200 WHERE name="Solid Star of Elune";
UPDATE item_template SET stackable=200 WHERE name="Soulbound Test Gem";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Nightseye";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Sky Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Star of Elune";
UPDATE item_template SET stackable=200 WHERE name="Stalwart Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Star of Elune";
UPDATE item_template SET stackable=200 WHERE name="Stark Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Stark Blood Garnet";
UPDATE item_template SET stackable=200 WHERE name="Stark Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Steady Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Steady Talasite";
UPDATE item_template SET stackable=200 WHERE name="Stormy Sky Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Stormy Star of Elune";
UPDATE item_template SET stackable=200 WHERE name="Subtle Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Subtle Scarlet Ruby";
UPDATE item_template SET stackable=200 WHERE name="Sundered Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Swift Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Swift Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Swift Starfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Swift Starflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Swift Windfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Talasite";
UPDATE item_template SET stackable=200 WHERE name="Teardrop Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Tenacious Earthstorm Diamond";
UPDATE item_template SET stackable=200 WHERE name="Tense Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Tenuous Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Test Dazzling Talasite";
UPDATE item_template SET stackable=200 WHERE name="Test Living Ruby";
UPDATE item_template SET stackable=200 WHERE name="Thick Autumn's Glow";
UPDATE item_template SET stackable=200 WHERE name="Thick Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Thundering Skyfire Diamond";
UPDATE item_template SET stackable=200 WHERE name="Thundering Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Timeless Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Tireless Skyflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Tireless Starflare Diamond";
UPDATE item_template SET stackable=200 WHERE name="Trenchant Earthshatter Diamond";
UPDATE item_template SET stackable=200 WHERE name="Trenchant Earthsiege Diamond";
UPDATE item_template SET stackable=200 WHERE name="Turbid Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Twilight Opal";
UPDATE item_template SET stackable=200 WHERE name="Unstable Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Unstable Citrine";
UPDATE item_template SET stackable=200 WHERE name="Unstable Peridot";
UPDATE item_template SET stackable=200 WHERE name="Unstable Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Unstable Talasite";
UPDATE item_template SET stackable=200 WHERE name="Unstable Topaz";
UPDATE item_template SET stackable=200 WHERE name="Veiled Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Veiled Noble Topaz";
UPDATE item_template SET stackable=200 WHERE name="Vivid Forest Emerald";
UPDATE item_template SET stackable=200 WHERE name="Wicked Monarch Topaz";
UPDATE item_template SET stackable=200 WHERE name="Wicked Noble Topaz";

/* Purple gems */
UPDATE item_template SET stackable=200 WHERE name="Accurate Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Assassin's Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Balanced Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Balanced Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Beaming Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Blessed Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Blood of Amber";
UPDATE item_template SET stackable=200 WHERE name="Bold Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bold Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Bold Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Bold Ornate Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bold Ornate Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bold Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Bright Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Bright Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Bright Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Bright Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Bladestone";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Brilliant King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Brilliant Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Brutal Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Champion's Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Champion's Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Charmed Amani Jewel";
UPDATE item_template SET stackable=200 WHERE name="Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Crimson Sun";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Dazzling Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Deadly Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Deadly Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Defender's Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Defender's Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Deft Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Delicate Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Delicate Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Delicate Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Delicate Fire Ruby";
UPDATE item_template SET stackable=200 WHERE name="Delicate Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Don Julio's Heart";
UPDATE item_template SET stackable=200 WHERE name="Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Durable Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Durable Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Effulgent Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Empowered Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Empowered Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Empyrean Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Enduring Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Enduring Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Enduring Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Energized Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Enscribed Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Etched Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Etched Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Facet of Eternity";
UPDATE item_template SET stackable=200 WHERE name="Falling Star";
UPDATE item_template SET stackable=200 WHERE name="Fierce Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Flashing Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Flashing Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Flashing Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Fluorescent Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Forceful Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Forceful Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Fractured Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Fractured Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Gleaming Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Gleaming Ornate Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Gleaming Ornate Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Glimmering Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Glimmering Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Glinting Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Glinting Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Glinting Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Glistening Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Glowing Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Glowing Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Glowing Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Great Bladestone";
UPDATE item_template SET stackable=200 WHERE name="Great Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Guardian's Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Imperial Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Infused Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Infused Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Infused Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Infused Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Ornate Topaz";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Ornate Topaz";
UPDATE item_template SET stackable=200 WHERE name="Inscribed Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Intricate Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Iridescent Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Jagged Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Jagged Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Jagged Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Kailee's Rose";
UPDATE item_template SET stackable=200 WHERE name="Kharmaa's Grace";
UPDATE item_template SET stackable=200 WHERE name="King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Lambent Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Lambent Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Lucent Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Luminous Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Luminous Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Luminous Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Empyrean Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Lustrous Majestic Zircon";
UPDATE item_template SET stackable=200 WHERE name="Majestic Zircon";
UPDATE item_template SET stackable=200 WHERE name="Misty Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Mysterious Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Mysterious Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Mystic Bladestone";
UPDATE item_template SET stackable=200 WHERE name="Mystic Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Mystic King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Mystic Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Nightmare Tear";
UPDATE item_template SET stackable=200 WHERE name="Nimble Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Omar's Gem of POWAH";
UPDATE item_template SET stackable=200 WHERE name="Opaque Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Polished Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Potent Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Potent Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Potent Ornate Topaz";
UPDATE item_template SET stackable=200 WHERE name="Potent Ornate Topaz";
UPDATE item_template SET stackable=200 WHERE name="Potent Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Precise Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Precise Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Pristine Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Pristine Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Puissant Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Pulsing Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Purified Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Purified Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Quick Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Quick King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Quick Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Radiant Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Radiant Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Radiant Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Radiant Spencerite";
UPDATE item_template SET stackable=200 WHERE name="Reckless Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Reckless Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Regal Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Regal Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Resolute Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Resplendent Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Resplendent Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Rigid Bladestone";
UPDATE item_template SET stackable=200 WHERE name="Rigid Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Rigid King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Rigid Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Rigid Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Royal Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Royal Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Royal Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Rune Covered Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Runed Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Runed Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Runed Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Runed Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Runed Ornate Ruby";
UPDATE item_template SET stackable=200 WHERE name="Runed Ornate Ruby";
UPDATE item_template SET stackable=200 WHERE name="Runed Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Seer's Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Seer's Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Shattered Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Shifting Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Shifting Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Shifting Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Shining Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Shining Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Smooth Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Smooth King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Smooth Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Smooth Ornate Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Smooth Ornate Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Solid Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Solid Empyrean Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Solid Majestic Zircon";
UPDATE item_template SET stackable=200 WHERE name="Solid Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Soothing Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Shadowsong Amethyst";
UPDATE item_template SET stackable=200 WHERE name="Sovereign Tanzanite";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Empyrean Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Falling Star";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Majestic Zircon";
UPDATE item_template SET stackable=200 WHERE name="Sparkling Stormjewel";
UPDATE item_template SET stackable=200 WHERE name="Splendid Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Stalwart Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Stalwart Fire Opal";
UPDATE item_template SET stackable=200 WHERE name="Stark Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Steady Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Steady Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Steady Seaspray Emerald";
UPDATE item_template SET stackable=200 WHERE name="Stone of Blades";
UPDATE item_template SET stackable=200 WHERE name="Stormy Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Stormy Empyrean Sapphire";
UPDATE item_template SET stackable=200 WHERE name="Stormy Majestic Zircon";
UPDATE item_template SET stackable=200 WHERE name="Sublime Mystic Dawnstone";
UPDATE item_template SET stackable=200 WHERE name="Subtle Cardinal Ruby";
UPDATE item_template SET stackable=200 WHERE name="Subtle Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Subtle Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Sundered Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Sundered Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Teardrop Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Teardrop Crimson Spinel";
UPDATE item_template SET stackable=200 WHERE name="Tense Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Tenuous Dreadstone";
UPDATE item_template SET stackable=200 WHERE name="Thick Dragon's Eye";
UPDATE item_template SET stackable=200 WHERE name="Thick King's Amber";
UPDATE item_template SET stackable=200 WHERE name="Thick Lionseye";
UPDATE item_template SET stackable=200 WHERE name="Timeless Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Timeless Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Turbid Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Veiled Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Veiled Pyrestone";
UPDATE item_template SET stackable=200 WHERE name="Vivid Chrysoprase";
UPDATE item_template SET stackable=200 WHERE name="Vivid Eye of Zul";
UPDATE item_template SET stackable=200 WHERE name="Void Sphere";
UPDATE item_template SET stackable=200 WHERE name="Wicked Ametrine";
UPDATE item_template SET stackable=200 WHERE name="Wicked Pyrestone";
