#!/bin/bash

while true
do
   battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
   # battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`
   if [ $battery_level -le 5 ]; then
      notify-send --urgency=CRITICAL "Battery critcal" "Level: ${battery_level}%"
      play /home/wow/wowsss/media/sounds/thats-not-funny.ogg
   elif [ $battery_level -le 15 ]; then
      notify-send "Battery Low" "Level: ${battery_level}%"
      play /home/wow/wowsss/media/sounds/thats-not-funny.ogg
   fi
   sleep 60
done
